// src/config.js
export const hookTitleMappings = {
    "Problem/Agitate/Solve": { en: "The Core Problem", id: "Inti Masalah" },
    "Before & After": { en: "The Transformation", id: "Transformasi" },
    "Story Hook": { en: "The Opening Story", id: "Pembuka Cerita" },
    "Question Hook": { en: "The Big Question", id: "Pertanyaan Utama" },
    "Contrarian Hook": { en: "The Surprising Truth", id: "Kebenaran Mengejutkan" },
    "Secret Hook": { en: "The Unveiled Secret", id: "Rahasia Terungkap" },
    "Statistic Hook": { en: "The Shocking Statistic", id: "Statistik Mengejutkan" },
    "Objection Hook": { en: "Addressing Doubts", id: "Mengatasi Keraguan" },
    "Testimonial Hook": { en: "Proof from Others", id: "Bukti dari Orang Lain" },
    "How-To Hook": { en: "The First Step", id: "Langkah Pertama" }
};

export const uiTextConfig = {
  en: {
    ...hookTitleMappings,
    supportAdmin: "Support Admin",
    affiliator: "Affiliator",
    threadsMate: "ThreadsMate",
    settings: "Settings",
    about: "About Us",
    contentType: "Content Type",
    singlePost: "Single Post",
    carousel: "Carousel",
    productName: "Product Name",
    productNamePlaceholder: "e.g., AnoTech Ergonomic Chair",
    productDesc: "Product Description",
    productDescPlaceholder: "Explain the main features, advantages, and benefits...",
    languageStyle: "Language Style",
    targetAudience: "Target Audience",
    hookType: "Hook Type",
    hookStyleTitle: "Hook Style",
    numberOfScripts: "Number of Scripts",
    numberOfSlides: "Number of Slides",
    generateButton: "Generate with AI",
    generatingButton: "Generating...",
    resetButton: "Reset",
    saveAsPdf: "Save as PDF",
    outputPlaceholderTitle: "Your generated content will appear here.",
    outputPlaceholderSubtitle: "Fill out the form and click \"Generate with AI\" to start.",
    errorTitle: "Failed to Generate Content",
    errorValidationTitle: "Incomplete Information",
    errorValidationMessage: "Please fill in all required fields before generating.",
    errorSetApiKey: "Please set your API Key in the Settings page before generating.",
    tryAgain: "Try Again",
    editAndRegenerate: "Edit & Regenerate",
    storytellingBody: "Storytelling Body",
    callToAction: "Call To Action",
    settingsTitle: "Settings",
    apiSettings: "API Settings",
    apiSettingsDesc: "Manage your API key to access external AI tools.",
    apiMode: "API Mode",
    apiModeDefault: "Use AnoTechHub's Default Key",
    apiModeCustom: "Use Your Own API Key",
    yourApiKey: "Your Gemini API Key",
    apiKeyPlaceholder: "Enter your API key here...",
    saveApiSettings: "Save API Settings",
    apiKeySaveWarning: "Don't forget to save your new settings.",
    systemPrompt: "System Instruction Prompt",
    systemPromptDesc: "This prompt will guide the AI's personality and response style.",
    affiliatorSystemPrompt: "Affiliator System Prompt",
    threadsMateSystemPrompt: "ThreadsMate System Prompt",
    promptInstruction: "Prompt Instruction",
    saveChanges: "Save Changes",
    activePrompt: "Active Prompt Instruction",
    downloadStarted: "Download Started!",
    thankYouMessage: "Thank you for using the Anotechhub generator. Have a great day!",
    close: "Close",
    apiKeyApplied: "API Key Applied!",
    apiKeyAppliedMessage: "Your API key has been saved and will be used for future requests.",
    settingsSaved: "Settings Saved!",
    settingsSavedMessage: "Your new settings have been successfully applied.",
    gotIt: "Got it",
    editAndRegenerateModalTitle: "Edit & Regenerate",
    originalVersion: "Original Version",
    newVersion: "New Version",
    aiIsWorking: "AI is working...",
    newVersionPlaceholder: "New version will appear here.",
    revisionInstructions: "Revision Instructions (Free Form)",
    revisionPlaceholder: "e.g., Make it funnier, target teenagers, use more formal language...",
    regenerate: "Regenerate",
    useThisVersion: "Use This Version",
    apiKeyWarning: "Note: This is a shared key and may have limitations. For the best experience, we highly recommend using your own API key.",
    initialSetupTitle: "Welcome to AnoTechHub!",
    initialSetupSubtitle: "To get started, please set up your API key in the settings. You can use our default key or add your own.",
    goToSettings: "Go to Settings",
    backToGenerator: "Back to Generator",
    mobilePreview: "Mobile Preview",
    copy: "Copy",
    copied: "Copied!",
    mainContentIdea: "Main Content Idea",
    mainContentIdeaPlaceholder: "e.g., 5 productive tips for programmers working from home",
    deliveryStyle: "Delivery Style",
    numberOfThreads: "Number of Threads (Series)",
    aboutTitle: "Welcome to AnoTechHub AI Generator",
    aboutSubtitle: "The smart solution for creating high-conversion marketing content quickly and effectively. We are here to help affiliate marketers, content creators, and business owners to produce engaging promotional materials with the power of AI.",
    aboutFeatureTitle: "Our Main Features",
    feature1Title: "Affiliator Content Generator",
    feature1Desc: "Create promotional scripts for single posts or carousels. Just input the product details, and let our AI craft compelling copy for you.",
    feature2Title: "ThreadsMate Content Generator",
    feature2Desc: "Design viral, serialized content for platforms like Threads & X. Generate a series of connected posts that are engaging and discussion-worthy.",
    feature3Title: "Powered by Gemini AI",
    feature3Desc: "Leveraging Google's advanced AI to deliver high-quality, relevant, and creative content tailored to your needs.",
    feature4Title: "Multi-Language Support",
    feature4Desc: "Available in both English and Indonesian to reach a wider audience.",
    feature5Title: "Full Customization",
    feature5Desc: "Adjust the language style, target audience, and even the AI's core instructions to get the perfect results.",
  },
  id: {
    ...hookTitleMappings,
    supportAdmin: "Dukungan Admin",
    affiliator: "Affiliator",
    threadsMate: "ThreadsMate",
    settings: "Pengaturan",
    about: "Tentang Kami",
    contentType: "Jenis Konten",
    singlePost: "Single Post",
    carousel: "Carousel",
    productName: "Nama Produk",
    productNamePlaceholder: "Contoh: Kursi Ergonomis AnoTech",
    productDesc: "Deskripsi Produk",
    productDescPlaceholder: "Jelaskan fitur utama, keunggulan, dan manfaat produk Anda...",
    languageStyle: "Gaya Bahasa",
    targetAudience: "Target Audience",
    hookType: "Jenis Hook",
    hookStyleTitle: "Gaya Hook",
    numberOfScripts: "Jumlah Script",
    numberOfSlides: "Jumlah Slide",
    generateButton: "Buat dengan AI",
    generatingButton: "Membuat...",
    resetButton: "Reset",
    saveAsPdf: "Simpan sebagai PDF",
    outputPlaceholderTitle: "Konten yang Anda buat akan muncul di sini.",
    outputPlaceholderSubtitle: "Isi formulir dan klik \"Buat dengan AI\" untuk memulai.",
    errorTitle: "Gagal Membuat Konten",
    errorValidationTitle: "Informasi Tidak Lengkap",
    errorValidationMessage: "Harap isi semua kolom yang diperlukan sebelum membuat konten.",
    errorSetApiKey: "Harap atur Kunci API Anda di halaman Pengaturan sebelum membuat.",
    tryAgain: "Coba Lagi",
    editAndRegenerate: "Edit & Regenerate",
    storytellingBody: "Isi Cerita",
    callToAction: "Call To Action",
    settingsTitle: "Pengaturan",
    apiSettings: "Pengaturan API",
    apiSettingsDesc: "Kelola kunci API Anda untuk mengakses tool AI eksternal.",
    apiMode: "Mode API",
    apiModeDefault: "Gunakan Kunci Default AnoTechHub",
    apiModeCustom: "Gunakan Kunci API Sendiri",
    yourApiKey: "Kunci API Gemini Anda",
    apiKeyPlaceholder: "Masukkan kunci API Anda di sini...",
    saveApiSettings: "Simpan Pengaturan API",
    apiKeySaveWarning: "Jangan lupa simpan pengaturan baru Anda.",
    systemPrompt: "System Instruction Prompt",
    systemPromptDesc: "Prompt ini akan mengarahkan kepribadian dan gaya respons AI.",
    affiliatorSystemPrompt: "System Prompt Affiliator",
    threadsMateSystemPrompt: "System Prompt ThreadsMate",
    promptInstruction: "Instruksi Prompt",
    saveChanges: "Simpan Perubahan",
    activePrompt: "Instruksi Prompt Aktif",
    downloadStarted: "Unduhan Dimulai!",
    thankYouMessage: "Terima kasih sudah menggunakan generator Anotechhub. Semoga harimu menyenangkan!",
    close: "Tutup",
    apiKeyApplied: "API Key Diterapkan!",
    apiKeyAppliedMessage: "Kunci API Anda telah disimpan dan akan digunakan untuk permintaan berikutnya.",
    settingsSaved: "Pengaturan Disimpan!",
    settingsSavedMessage: "Pengaturan baru Anda telah berhasil diterapkan.",
    gotIt: "Mengerti",
    editAndRegenerateModalTitle: "Edit & Regenerate",
    originalVersion: "Versi Asli",
    newVersion: "Versi Baru",
    aiIsWorking: "AI sedang bekerja...",
    newVersionPlaceholder: "Versi baru akan muncul di sini.",
    revisionInstructions: "Instruksi Revisi (Free Form)",
    revisionPlaceholder: "Contoh: Buat lebih lucu, targetkan untuk remaja, gunakan bahasa yang lebih formal...",
    regenerate: "Regenerate",
    useThisVersion: "Gunakan Versi Ini",
    apiKeyWarning: "Catatan: Kunci ini digunakan bersama dan mungkin memiliki batasan. Untuk pengalaman terbaik, kami sangat menyarankan menggunakan kunci API Anda sendiri.",
    initialSetupTitle: "Selamat Datang di AnoTechHub!",
    initialSetupSubtitle: "Untuk memulai, harap atur kunci API Anda di pengaturan. Anda dapat menggunakan kunci default kami atau menambahkan kunci Anda sendiri.",
    goToSettings: "Buka Pengaturan",
    backToGenerator: "Kembali ke Generator",
    mobilePreview: "Pratinjau Seluler",
    copy: "Salin",
    copied: "Tersalin!",
    mainContentIdea: "Ide Konten Utama",
    mainContentIdeaPlaceholder: "Contoh: 5 tips produktif bagi programmer yang bekerja dari rumah",
    deliveryStyle: "Gaya Penyampaian",
    numberOfThreads: "Jumlah Konten (Series)",
    aboutTitle: "Selamat Datang di AnoTechHub AI Generator",
    aboutSubtitle: "Solusi cerdas untuk membuat konten marketing berkonversi tinggi secara cepat dan efektif. Kami hadir untuk membantu para affiliate marketer, content creator, dan pemilik bisnis untuk menghasilkan materi promosi yang menarik dengan kekuatan AI.",
    aboutFeatureTitle: "Fitur Utama Kami",
    feature1Title: "Generator Konten Affiliator",
    feature1Desc: "Buat skrip promosi untuk single post atau carousel. Cukup masukkan detail produk, dan biarkan AI kami menyusun copy yang memikat untuk Anda.",
    feature2Title: "Generator Konten ThreadsMate",
    feature2Desc: "Rancang konten viral berseri untuk platform seperti Threads & X. Hasilkan serangkaian post yang terhubung, menarik, dan memancing diskusi.",
    feature3Title: "Didukung oleh Gemini AI",
    feature3Desc: "Memanfaatkan AI canggih dari Google untuk memberikan konten berkualitas tinggi, relevan, dan kreatif yang disesuaikan dengan kebutuhan Anda.",
    feature4Title: "Dukungan Multi-Bahasa",
    feature4Desc: "Tersedia dalam Bahasa Inggris dan Bahasa Indonesia untuk menjangkau audiens yang lebih luas.",
    feature5Title: "Kustomisasi Penuh",
    feature5Desc: "Sesuaikan gaya bahasa, target audiens, dan bahkan instruksi inti AI untuk mendapatkan hasil yang sempurna.",
  }
};

export const systemPrompts = {
    affiliator: {
        en: "You are 'Anoboy', an expert AI copywriter specializing in high-conversion affiliate marketing scripts for social media. Your goal is to create content that feels authentic, engaging, and drives action.\n\n**Your Task:** Generate a script or carousel content based on the user's inputs.\n\n**Key Instructions:**\n1.  **Hook First:** Always start with a strong hook based on the 'Hook Type' provided by the user.\n2.  **Target Audience:** Deeply consider the 'Target Audience'. Use language that resonates with them.\n3.  **Structure (for Single Post):** Follow Title -> Problem/Hook -> Story/Solution -> Call to Action (CTA).\n4.  **Structure (for Carousel):** Create distinct points for each slide. The title of each slide should be short and punchy.\n5.  **Language of Response:** Respond ONLY in the requested language (English or Indonesian).",
        id: "Anda adalah 'Anoboy', seorang copywriter AI ahli yang berspesialisasi dalam skrip pemasaran afiliasi media sosial dengan konversi tinggi. Tujuan Anda adalah membuat konten yang terasa otentik, menarik, dan mendorong tindakan.\n\n**Tugas Anda:** Buat skrip atau konten carousel berdasarkan input pengguna.\n\n**Instruksi Utama:**\n1.  **Hook Terlebih Dahulu:** Selalu mulai dengan hook yang kuat berdasarkan 'Jenis Hook' yang diberikan pengguna.\n2.  **Target Audiens:** Pertimbangkan 'Target Audiens' secara mendalam. Gunakan bahasa yang beresonansi dengan mereka.\n3.  **Struktur (untuk Single Post):** Ikuti alur Judul -> Masalah/Hook -> Cerita/Solusi -> Call to Action (CTA).\n4.  **Struktur (untuk Carousel):** Buat poin-poin yang berbeda untuk setiap slide. Judul setiap slide harus singkat dan kuat.\n5.  **Bahasa Respons:** Balas HANYA dalam bahasa yang diminta (Inggris atau Indonesia)."
    },
    threadsMate: {
        en: "You are 'ThreadsMate AI', an expert in creating viral, serialized content for platforms like Threads and Twitter. Your goal is to generate a series of connected posts that are engaging, easy to read, and encourage discussion.\n\n**Your Task:** Generate a series of threads based on the user's inputs.\n\n**Key Instructions:**\n1.  **Create a Series:** The threads MUST be a connected series.\n2.  **Hook is Crucial:** The first thread (1/N) MUST BE the hook, based on the 'Hook Type' to grab attention immediately.\n3.  **Build Up:** Each subsequent thread builds upon the previous one.\n4.  **Numbered List Format:** Use a numbered format for clarity (e.g., 1/10, 2/10).\n5.  **End with a Follow CTA:** The final thread MUST contain a clear Call to Action prompting the user to follow for more content.\n6.  **Tone & Style:** Adapt your tone based on the requested 'Delivery Style' and 'Language Style'.\n7.  **Language of Response:** Respond ONLY in the requested language (English or Indonesian).",
        id: "Anda adalah 'ThreadsMate AI', seorang ahli dalam membuat konten viral berseri untuk platform seperti Threads dan Twitter. Tujuan Anda adalah menghasilkan serangkaian post yang terhubung, menarik, mudah dibaca, dan mendorong diskusi.\n\n**Tugas Anda:** Buat serangkaian thread berdasarkan input pengguna.\n\n**Instruksi Utama:**\n1.  **Buat Konten Berseri:** Thread HARUS merupakan seri yang terhubung.\n2.  **Hook Sangat Penting:** Thread pertama (1/N) HARUS menjadi hook yang kuat berdasarkan 'Jenis Hook' untuk langsung menarik perhatian.\n3.  **Membangun Cerita:** Setiap thread berikutnya membangun dari yang sebelumnya.\n4.  **Format Daftar Bernomor:** Gunakan format bernomor agar jelas (misal: 1/10, 2/10).\n5.  **Akhiri dengan CTA Follow:** Thread terakhir HARUS berisi Call to Action yang jelas yang mengajak pengguna untuk follow agar mendapatkan konten lebih lanjut.\n6.  **Nada & Gaya:** Sesuaikan nada Anda berdasarkan 'Gaya Penyampaian' dan 'Gaya Bahasa' yang diminta.\n7.  **Bahasa Respons:** Balas HANYA dalam bahasa yang diminta (Inggris atau Indonesia)."
    }
};